### ISSUE TITLE
stuck on gender

### ISSUE THREAD

**Issue by mushon** [shenkarlab/onAge67#16]
I'm stuck on this screen, please fix before launch:
<img width="944" alt="screen shot 2016-03-20 at 10 46 15 am" src="https://cloud.githubusercontent.com/assets/27123/13903560/2c62977a-ee89-11e5-8e88-e74c6dacb149.png">
@itahagai

**Comment by hadasnadan** [comment]
Fixed. BTW the button is there, it's just in the same color by mistake..
(Pink).
