### ISSUE TITLE
יש צורך ביותר נוכחות לקרדיט של שנקר באתר

### ISSUE THREAD

**Issue by mushon** [shenkarlab/onAge67#18]
@itahagai @shaulams 
אנחנו נרצה לראות את הקרדיט גם בדף הראשון וגם בדף האחרון.
זה פרויקט יפה, נשמח להנות ממנו. הלוגו של שנקר צריך לקשר חזרה לאתר שנקר.

מעבר לזה צריך להופיע טקסט שמסביר שהפרויקט פותח במסגרת מעבדת הדאטה-ג׳ורנליזם של שנקר וכלכליסט.

**Comment by shaulams** [comment]
יש טקסט כזה

**Comment by mushon** [comment]
לינק?

**Comment by shaulams** [comment]
ובכן, טעיתי, חשבתי שזה קיים במסגרת ההסבר איך הגענו לזה

**Comment by mushon** [comment]
סבבה, אני מבין שזו עדיין לא הגרסה האחרונה.
אני אשמח לראות התייחסות למעבדת הדאטה-ג׳ורנליזם בדברי הסבר
וגם קרדיטים לשנקר בדף הראשון והאחרון (finish.html) של האפליקציה.

פרויקט נהדר!
